In [9]:
import numpy as np
from numpy import linalg as la
A=np.array([[1,2,3],[0,-4,1],[0,3,-1]])
b=np.array([1,1,-2])
det = la.det(A)
print(f"Determinant of A is: {det:.6f}")
X = la.solve(A,b )  # Unpacking is also possible with NumPy arrays
print(A, ".(x,y,z) =", X)
print(f"\nA.AT should be the identity matrix:\n{A@A.T}\n{A@A.T == np.identity(3)}")
Lambda, v = la.eig(A)
print("Lambda = ", Lambda)
print(f"\nEigenvectors:\n{v}")

Determinant of A is: 1.000000
[[ 1  2  3]
 [ 0 -4  1]
 [ 0  3 -1]] .(x,y,z) = [-16.   1.   5.]

A.AT should be the identity matrix:
[[ 14  -5   3]
 [ -5  17 -13]
 [  3 -13  10]]
[[False False False]
 [False False False]
 [False False False]]
Lambda =  [ 1.         -4.79128785 -0.20871215]

Eigenvectors:
[[ 1.         -0.05055961  0.94256676]
 [ 0.         -0.78318743 -0.08518794]
 [ 0.          0.6197267  -0.32297201]]
